package completecmd

import (
	"fmt"
	"io"
	"strings"
)

const initZsh = `# Generated by: complete init zsh
# Add to ~/.zshrc: eval "$(complete init zsh)"
function complete() {
  eval "$(command complete --shell=zsh "$@")"
}
`

const initBash = `# Generated by: complete init bash
# Add to ~/.bashrc: eval "$(complete init bash)"
function compx() {
  eval "$(command complete --shell=bash "$@")"
}
`

func emitInit(shell string, stdout, stderr io.Writer) int {
	switch strings.ToLower(shell) {
	case "zsh":
		fmt.Fprint(stdout, initZsh)
	case "bash":
		fmt.Fprint(stdout, initBash)
	default:
		fmt.Fprintf(stderr, "complete init: unsupported shell %q (supported: zsh bash)\n", shell)
		return 1
	}
	return 0
}
